In [1]:
import numpy as np

data=np.linspace(1,2,10).reshape(5,2)

# Aggregate Functions

In [2]:
# Aggregation functions
mean_value = np.mean(data)
sum_value = np.sum(data)
max_value = np.max(data)

print("Mean:", mean_value)
print("Sum:", sum_value)
print("Max:", max_value)

Mean: 1.5
Sum: 15.0
Max: 2.0


# Joining and Splitting

In [10]:
# Splitting
split_data = np.split(data, [2, 5])  # Split at indices 2 and 5

print("Original Data:", data)
print("\nSplit Data:", split_data)

# Joining

concatenated = np.concatenate((data, data))  # Default axis is 0 (rows)
print("\nConcatenated:", concatenated)

concatenated_data = np.concatenate((data, data), axis=1)
print("\nConcatenate (Axis=1):")
print(concatenated_data)
print()



split_data = np.vsplit(data, 5)
print("Splitting (Vertical Split):")
print(split_data)
print()

Original Data: [[1.         1.11111111]
 [1.22222222 1.33333333]
 [1.44444444 1.55555556]
 [1.66666667 1.77777778]
 [1.88888889 2.        ]]

Split Data: [array([[1.        , 1.11111111],
       [1.22222222, 1.33333333]]), array([[1.44444444, 1.55555556],
       [1.66666667, 1.77777778],
       [1.88888889, 2.        ]]), array([], shape=(0, 2), dtype=float64)]

Concatenated: [[1.         1.11111111]
 [1.22222222 1.33333333]
 [1.44444444 1.55555556]
 [1.66666667 1.77777778]
 [1.88888889 2.        ]
 [1.         1.11111111]
 [1.22222222 1.33333333]
 [1.44444444 1.55555556]
 [1.66666667 1.77777778]
 [1.88888889 2.        ]]

Concatenate (Axis=1):
[[1.         1.11111111 1.         1.11111111]
 [1.22222222 1.33333333 1.22222222 1.33333333]
 [1.44444444 1.55555556 1.44444444 1.55555556]
 [1.66666667 1.77777778 1.66666667 1.77777778]
 [1.88888889 2.         1.88888889 2.        ]]

Splitting (Vertical Split):
[array([[1.        , 1.11111111]]), array([[1.22222222, 1.33333333]]), array([[1.4

# Stack

In [11]:
stacked_data = np.stack([data, data], axis=0)
print("Stacked Data:")
print(stacked_data)
print()

# vstack (Vertical Stack)
vstacked_data = np.vstack([data, data])
print("\nVertical Stack:")
print(vstacked_data)
print()

# hstack (Horizontal Stack)
hstacked_data = np.hstack([data, data])
print("\nHorizontal Stack:")
print(hstacked_data)
print()

# column_stack
column_stacked_data = np.column_stack([data, data])
print("\nColumn Stack:")
print(column_stacked_data)

Stacked Data:
[[[1.         1.11111111]
  [1.22222222 1.33333333]
  [1.44444444 1.55555556]
  [1.66666667 1.77777778]
  [1.88888889 2.        ]]

 [[1.         1.11111111]
  [1.22222222 1.33333333]
  [1.44444444 1.55555556]
  [1.66666667 1.77777778]
  [1.88888889 2.        ]]]


Vertical Stack:
[[1.         1.11111111]
 [1.22222222 1.33333333]
 [1.44444444 1.55555556]
 [1.66666667 1.77777778]
 [1.88888889 2.        ]
 [1.         1.11111111]
 [1.22222222 1.33333333]
 [1.44444444 1.55555556]
 [1.66666667 1.77777778]
 [1.88888889 2.        ]]


Horizontal Stack:
[[1.         1.11111111 1.         1.11111111]
 [1.22222222 1.33333333 1.22222222 1.33333333]
 [1.44444444 1.55555556 1.44444444 1.55555556]
 [1.66666667 1.77777778 1.66666667 1.77777778]
 [1.88888889 2.         1.88888889 2.        ]]


Column Stack:
[[1.         1.11111111 1.         1.11111111]
 [1.22222222 1.33333333 1.22222222 1.33333333]
 [1.44444444 1.55555556 1.44444444 1.55555556]
 [1.66666667 1.77777778 1.66666667 1.777