In [18]:
import numpy as np
from numpy import random

In [19]:
matrix = np.array([[-1,0,1],[-1,-1,0],[0,1,-1]])

In [20]:
boolean_mask = matrix >= 0
boolean_mask

array([[False,  True,  True],
       [False, False,  True],
       [ True,  True, False]])

In [21]:
filtered = matrix[boolean_mask]
filtered

array([0, 1, 0, 0, 1])

In [22]:
row_mask = matrix[:, 1] >= 0
col_mask = matrix[0,:] >= 0

selected_rows = matrix[row_mask]
selected_rows

array([[-1,  0,  1],
       [ 0,  1, -1]])

In [23]:
i=0
for col in matrix:
    if col[i]== -1:
        print(col[i])
        i += 1

-1
-1
-1


In [24]:
for i, col in enumerate(matrix.T):
    print(f"This is output for col {i+1}: {col}")
    print(f"\nThis is output for col{i+1}: {col[col==1]}")

This is output for col 1: [-1 -1  0]

This is output for col1: []
This is output for col 2: [ 0 -1  1]

This is output for col2: [1]
This is output for col 3: [ 1  0 -1]

This is output for col3: [1]


In [25]:
for i, col in enumerate(matrix.T):  # Transpose the matrix to iterate over columns
    sum_of_minus_ones = np.sum(col == -1)  # Calculate the sum of -1 elements in the column
    print(f"Sum of -1s in column {i + 1}: {sum_of_minus_ones}")

Sum of -1s in column 1: 2
Sum of -1s in column 2: 1
Sum of -1s in column 3: 1


In [26]:
for i, col in enumerate(matrix.T):  # Transpose the matrix to iterate over columns
    column_avg = np.sum(col)/len(col) 
    print(f"Avg column {i + 1}: {column_avg}")
    valid_values = col[col != -1]
    column_avg_valid = np.mean(valid_values)
    print(f"\nColumn {i + 1} average (excluding -1): {column_avg_valid}")

Avg column 1: -0.6666666666666666

Column 1 average (excluding -1): 0.0
Avg column 2: 0.0

Column 2 average (excluding -1): 0.5
Avg column 3: 0.0

Column 3 average (excluding -1): 0.5


#Assessment: Numpy Case Study


**Problem Statement:** 

A movie review website needs to create a database to store their data and perform operations on it. Create a dummy model with 100 users and 1000 movies to explain how it will work.

**Topics Covered:**
- NumPy
    - numpy.ndarray
    - Statistical operations using NumPy
    - Mathematical operations using NumPy
    
**Tasks to be performed:**
1. Generate 1000 movie IDs starting from 1301
2. Create a matrix movies_matrix, to store users rating such that
    - There are 100 users
    - Each user can review as many movies as they want
    - The review should be in between 0 to 10 (both inclusive)
3. We have ten movie experts, let us take their reviews as well. 50 new movies and their reviews have to be added 
4. Create final_movie_rating matrix with four columns i.e., 'Movie ID', 'Average rating', 'Number of ratings', and           'Standard deviation of ratings'


Bonus Questions

5. Display the movies rating-wise, highest to lowest

6. Store the array in a file and save it (file handling in Numpy)

In [27]:
# for col in zip(*matrix)
# for row in matrix


In [28]:
import numpy as np
from numpy import random

In [29]:
ratings_matrix_one = random.choice([-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], size=(100, 1000))

In [30]:
ratings_matrix_one

array([[ 1,  5,  5, ..., 10,  0,  1],
       [ 6,  3,  5, ...,  9,  6,  4],
       [ 4,  8,  6, ...,  8,  7,  9],
       ...,
       [10, -1,  8, ...,  3,  4,  9],
       [ 7,  3,  6, ..., 10, 10, -1],
       [ 3, -1, -1, ...,  8,  3,  5]])

In [57]:
import pandas as pd
movie_id = [x for x in range(1301, 2301)] 
movie_ratings_df = pd.DataFrame(movie_id)

In [58]:
print(movie_ratings_df)
print(movie_id)
movie_ratings_df.columns= ["movie_id"]


        0
0    1301
1    1302
2    1303
3    1304
4    1305
..    ...
995  2296
996  2297
997  2298
998  2299
999  2300

[1000 rows x 1 columns]
[1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 14

In [31]:
# Calculate the sum of -1 elements in the column
for i, col in enumerate(ratings_matrix_one.T):  # Transpose the matrix to iterate over columns
    sum_of_minus_ones = np.sum(col == -1)  # Calculate the sum of -1 elements in the column
    print(f"Sum of -1s in column {i + 1}: {sum_of_minus_ones}")

Sum of -1s in column 1: 7
Sum of -1s in column 2: 13
Sum of -1s in column 3: 7
Sum of -1s in column 4: 7
Sum of -1s in column 5: 7
Sum of -1s in column 6: 12
Sum of -1s in column 7: 13
Sum of -1s in column 8: 11
Sum of -1s in column 9: 7
Sum of -1s in column 10: 8
Sum of -1s in column 11: 10
Sum of -1s in column 12: 11
Sum of -1s in column 13: 8
Sum of -1s in column 14: 11
Sum of -1s in column 15: 10
Sum of -1s in column 16: 8
Sum of -1s in column 17: 9
Sum of -1s in column 18: 5
Sum of -1s in column 19: 11
Sum of -1s in column 20: 9
Sum of -1s in column 21: 8
Sum of -1s in column 22: 12
Sum of -1s in column 23: 7
Sum of -1s in column 24: 9
Sum of -1s in column 25: 10
Sum of -1s in column 26: 7
Sum of -1s in column 27: 11
Sum of -1s in column 28: 3
Sum of -1s in column 29: 14
Sum of -1s in column 30: 11
Sum of -1s in column 31: 12
Sum of -1s in column 32: 3
Sum of -1s in column 33: 10
Sum of -1s in column 34: 11
Sum of -1s in column 35: 7
Sum of -1s in column 36: 7
Sum of -1s in column

In [63]:
# Calculate the Average of all ratings in the column

for i, col in enumerate(ratings_matrix_one.T):  # Transpose the matrix to iterate over columns
    average_column = np.mean(col)
    print(f"Columnwise_Average {i + 1}: {average_column}")

Columnwise_Average 1: 4.36
Columnwise_Average 2: 4.09
Columnwise_Average 3: 4.63
Columnwise_Average 4: 4.45
Columnwise_Average 5: 4.72
Columnwise_Average 6: 4.28
Columnwise_Average 7: 4.08
Columnwise_Average 8: 4.22
Columnwise_Average 9: 4.42
Columnwise_Average 10: 4.42
Columnwise_Average 11: 4.4
Columnwise_Average 12: 5.05
Columnwise_Average 13: 5.07
Columnwise_Average 14: 4.48
Columnwise_Average 15: 4.57
Columnwise_Average 16: 4.82
Columnwise_Average 17: 4.4
Columnwise_Average 18: 4.65
Columnwise_Average 19: 4.17
Columnwise_Average 20: 4.76
Columnwise_Average 21: 5.0
Columnwise_Average 22: 4.47
Columnwise_Average 23: 4.53
Columnwise_Average 24: 4.36
Columnwise_Average 25: 4.2
Columnwise_Average 26: 4.17
Columnwise_Average 27: 4.63
Columnwise_Average 28: 5.14
Columnwise_Average 29: 4.05
Columnwise_Average 30: 3.87
Columnwise_Average 31: 4.19
Columnwise_Average 32: 5.33
Columnwise_Average 33: 4.72
Columnwise_Average 34: 3.72
Columnwise_Average 35: 4.38
Columnwise_Average 36: 3.85
Colum

In [48]:
average = []
for i, col in enumerate(ratings_matrix_one.T):    
    valid_values = col[col != -1]
    column_avg_valid = np.mean(valid_values)
    average.append(column_avg_valid)
    print(f"\nColumn {i + 1} average (excluding -1): {column_avg_valid}")


Column 1 average (excluding -1): 4.763440860215054

Column 2 average (excluding -1): 4.850574712643678

Column 3 average (excluding -1): 5.053763440860215

Column 4 average (excluding -1): 4.860215053763441

Column 5 average (excluding -1): 5.150537634408602

Column 6 average (excluding -1): 5.0

Column 7 average (excluding -1): 4.839080459770115

Column 8 average (excluding -1): 4.865168539325842

Column 9 average (excluding -1): 4.827956989247312

Column 10 average (excluding -1): 4.891304347826087

Column 11 average (excluding -1): 5.0

Column 12 average (excluding -1): 5.797752808988764

Column 13 average (excluding -1): 5.5978260869565215

Column 14 average (excluding -1): 5.157303370786517

Column 15 average (excluding -1): 5.188888888888889

Column 16 average (excluding -1): 5.326086956521739

Column 17 average (excluding -1): 4.934065934065934

Column 18 average (excluding -1): 4.947368421052632

Column 19 average (excluding -1): 4.808988764044944

Column 20 average (excluding

In [52]:
print(len(average))
print(movie_ratings_df.shape)

1000
(1001, 1)


In [59]:
movie_ratings_df['avg_rating'] = average

# Standard Deviation

In [60]:
std_deviations = []

for i, col in enumerate(ratings_matrix_one.T):    
    valid_values = col[col != -1]
    column_std_valid = np.std(valid_values)
    std_deviations.append(column_std_valid)

In [61]:
movie_ratings_df['std_deviation'] = std_deviations

In [62]:
movie_ratings_df

movie_id  avg_rating  std_deviation
0        1301    4.763441       3.066986
1        1302    4.850575       2.977034
2        1303    5.053763       3.038695
3        1304    4.860215       3.258047
4        1305    5.150538       3.047813
..        ...         ...            ...
995      2296    4.912088       3.133121
996      2297    4.989130       3.184523
997      2298    5.831579       3.093806
998      2299    5.043011       2.939951
999      2300    5.204301       3.003794

[1000 rows x 3 columns]

# Madam's Way

In [34]:
# 1. Initial values in matrix = -1 --- None of the movie is rated.
ratings_matrix = np.full((100,1000), -1)

In [35]:
ratings_matrix

array([[-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       ...,
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1]])

In [36]:
# 2. Replace -1 corresponding to each user for a random number of movies randomly with any number between 0 & 10

for user_index in range(100):
    # 3. Randomly choose the number of movies rated for this user (between 1 to 1000)
    num_movies_rated = np.random.randint(1, 1001)
    
    # 4. Randomly choose indices to update
    movie_indices = np.random.choice(1000, size=num_movies_rated, replace=False)
    
    # 5. Generate random ratings for 'num_movies_rated' movies
    random_ratings = np.random.uniform(low=0, high=10, size=num_movies_rated)
    
    # 6. Update the corresponding elements in the matrix
    ratings_matrix[user_index, movie_indices] = random_ratings

In [37]:
ratings_matrix

array([[ 8, -1, -1, ..., -1,  9,  1],
       [ 9,  4, -1, ..., -1,  3,  9],
       [-1,  6, -1, ...,  7, -1, -1],
       ...,
       [-1, -1,  1, ..., -1, -1,  0],
       [-1, -1, -1, ..., -1,  0, -1],
       [-1, -1, -1, ..., -1,  2, -1]])