In [1]:
ques = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [3]:
tokenizer = Tokenizer()

In [4]:
tokenizer.fit_on_texts([ques])

In [5]:
tokenizer.word_index

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'have': 8,
 'will': 9,
 'can': 10,
 'what': 11,
 'course': 12,
 'program': 13,
 'in': 14,
 'for': 15,
 'all': 16,
 'sessions': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'this': 21,
 'if': 22,
 'am': 23,
 'pay': 24,
 'payment': 25,
 'make': 26,
 'we': 27,
 'do': 28,
 'subscription': 29,
 'where': 30,
 'rs': 31,
 'so': 32,
 'campusx': 33,
 'session': 34,
 'our': 35,
 'paid': 36,
 'join': 37,
 'able': 38,
 'your': 39,
 'website': 40,
 'placement': 41,
 'fee': 42,
 'data': 43,
 'monthly': 44,
 'month': 45,
 'not': 46,
 'get': 47,
 'yes': 48,
 'once': 49,
 'past': 50,
 'feb': 51,
 'assistance': 52,
 'science': 53,
 '7': 54,
 '5600': 55,
 'are': 56,
 'watch': 57,
 'google': 58,
 'by': 59,
 'com': 60,
 'mail': 61,
 'from': 62,
 'contact': 63,
 'us': 64,
 'at': 65,
 'or': 66,
 'doubt': 67,
 'mentorship': 68,
 'payments': 69,
 '799': 70,
 'total': 71,
 'duration': 72,
 'months': 73,
 'learning': 74,
 'case': 75,
 'here': 76,
 '

In [16]:
input_sequence = []
for sent in ques.split("\n"):
    print(sent)
    tokenized_sent = tokenizer.texts_to_sequences([sent])[0]
    print(tokenized_sent)
    for i in range(1,len(tokenized_sent)):
        input_sequence.append(tokenized_sent[:i+1])

About the Program
[93, 1, 13]
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
[11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147, 148]
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
[1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31, 70, 45]
What is the total duration of the course?
[11, 7, 1, 71, 72, 6, 1, 12]
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
[1, 71, 72, 6, 1, 12, 7, 54, 73, 32, 1, 71, 12, 42, 149, 70, 54, 31, 55, 150]
What is the syllabus of the mentorship program?
[11, 7, 1, 96, 6, 1, 68, 13]
We will be covering the following modules:
[27, 9, 19, 151, 1, 152, 153]
Python Fundamentals
[97, 154]
Python libraries for Data Science
[97, 155, 15, 43, 53]
Data Analysis
[43, 156]
SQL for Data Science
[157, 15, 43, 53]
Maths for Machine Learning
[158, 15, 159, 74]
ML Algorithms
[98, 160]
Practical ML
[161, 98]
MLOPs
[162]
Case studies
[75, 99]

In [17]:
input_sequence.shape

AttributeError: 'list' object has no attribute 'shape'

# Padding

In [8]:
max_len = max([len(i) for i in input_sequence])
print(max_len)

57


In [9]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_seq = pad_sequences(input_sequence, maxlen = max_len)
print(padded_seq)

[[  0   0   0 ...   0  93   1]
 [  0   0   0 ...  93   1  13]
 [  0   0   0 ...   0  11   7]
 ...
 [  0   0   0 ... 279  18 280]
 [  0   0   0 ...  18 280 281]
 [  0   0   0 ... 280 281 282]]


In [10]:
X = padded_seq[:,:-1]# all columns
y = padded_seq[:,-1]# rowwise
print(f"Shape of X is {X.shape} and shape of y is {y.shape}")

Shape of X is (863, 56) and shape of y is (863,)


OHE

In [11]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes= len(tokenizer.word_index)+1)
print("shape y: ", y.shape)

shape y:  (863, 283)


# mOdle/

In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding

model = Sequential()
model.add(Embedding(283, 100, input_length = 56))
model.add(LSTM(160))
model.add(Dense(283,activation = "softmax"))

model.compile(optimizer = "adam", loss = "categorical_crossentropy", metrics = ["accuracy"])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 56, 100)           28300     
                                                                 
 lstm (LSTM)                 (None, 160)               167040    
                                                                 
 dense (Dense)               (None, 283)               45563     
                                                                 
Total params: 240,903
Trainable params: 240,903
Non-trainable params: 0
_________________________________________________________________


In [13]:
from tensorflow.keras.callbacks import ModelCheckpoint

filepath = "best_model.h5"

checkpoint = ModelCheckpoint(filepath, monitor='accuracy', verbose=1, save_best_only=True, mode='max')
history = model.fit(X, y, epochs=900, batch_size=32, callbacks=[checkpoint])

Epoch 1/900
27/27 [==============================] - ETA: 0s - loss: 5.4374 - accuracy: 0.0672
Epoch 1: accuracy improved from -inf to 0.06721, saving model to best_model.h5
27/27 [==============================] - 4s 79ms/step - loss: 5.4374 - accuracy: 0.0672
Epoch 2/900
27/27 [==============================] - ETA: 0s - loss: 5.0882 - accuracy: 0.0776
Epoch 2: accuracy improved from 0.06721 to 0.07764, saving model to best_model.h5
27/27 [==============================] - 2s 83ms/step - loss: 5.0882 - accuracy: 0.0776
Epoch 3/900
27/27 [==============================] - ETA: 0s - loss: 5.0183 - accuracy: 0.0776
Epoch 3: accuracy did not improve from 0.07764
27/27 [==============================] - 2s 81ms/step - loss: 5.0183 - accuracy: 0.0776
Epoch 4/900
27/27 [==============================] - ETA: 0s - loss: 4.9842 - accuracy: 0.0776
Epoch 4: accuracy did not improve from 0.07764
27/27 [==============================] - 2s 81ms/step - loss: 4.9842 - accuracy: 0.0776
Epoch 5/900
2

KeyboardInterrupt: 

In [ ]:
for i in range(20):
    tokenized_text = tokenize.texts_to_sequence([text])[0]
    #padding
    padded_token = padded_seq([tokenized_text], maxlen=56)
    predicted_token = np.argmax(model.predict(padded_token))
    for word, index in token.word_index.items():
        if index == predicted_token:
            text = text + " " + word
            print(text)